description: "Kubat Bayrıbey'in kişisel blogu. Tüm hakları saklıdır."
baseurl: "/web"  # Eğer kökte çalıştıracaksan bunu boş bırak: baseurl: ""
url: "https://kubat02.github.io"
theme: minima
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate # Sayfalama için
  - jemoji # Emoji desteği için
exclude:
  - README.md
  - _posts
  - _sass
  - assets
  - _includes
  - _layouts
  - .gitignore
  - Gemfile
  - Gemfile.lock
