title: My GitHub Pages Blog
description: A blog system with auto-updating sidebar for GitHub Pages.
baseurl: "/blog"  # Eğer kökte çalıştıracaksan bunu boş bırak: baseurl: ""
url: "https://kubat02.github.io"
theme: minima
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
exclude:
  - README.md
  - _posts
  - _sass
  - assets
  - _includes
  - _layouts
