title: Kisiel Blog
description: {{ site.year }} Your Name. All rights reserved.</p>
baseurl: "/web"  # Eğer kökte çalıştıracaksan bunu boş bırak: baseurl: ""
url: "https://kubat02.github.io"
theme: minima
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
exclude:
  - README.md
  - _posts
  - _sass
  - assets
  - _includes
  - _layouts
